/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.esotericsoftware:kryo:4.0.0")
    api("com.esotericsoftware:jsonbeans:0.7")
//    api(libs.com.esotericsoftware.kryo.kryo)
//    api(libs.com.esotericsoftware.jsonbeans)
//    testImplementation(libs.junit.junit)
}

group = "com.github.dmccabe"
version = "2.22.0-RC2"
description = "kryonet"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
